### PR TITLE
Fix reloading non-root urls when asset-path is set

### LINKED ISSUE #43: Reloading ClojureScript doesn't work for non-root browser path if asset-path is set
Our project is setup to serve assets from `/resources/public`. Task options is like this:
```
(task-options!
 cljs {:compiler-options {:asset-path "/application.out"}}
 reload {:asset-path "public" :on-jsload 'filemporium.client.core/on-reload})
```
When I'm at 
`http://localhost:3000/users/1/folder/1` on save it tries to reload url
`http://localhost:3000/users/1/folder/application.out/filemporium/client/ui/profile_new.js` instead of
`http://localhost:3000/application.out/filemporium/client/ui/profile_new.js`

### PR DESCRIPTION
**Pull request by alesguzik**
This fixes #43

### CODE REVIEW

**Comment by Deraen** [comment]
Looks like this would always use absolute paths for asset-path. I don't think that's desire.

**Comment by alesguzik** [comment]
@Deraen could you list a case when asset path would be relative to current url? I can't think of such a case.

**Comment by alesguzik** [comment]
In any case I may think of one have something like application.js at fixed path, probably with other cljs compiled files at some other fixed path. Why would asset path depend on your application route? And how would that even would be implemented?

**Comment by Deraen** [comment]
Hmh, I was thinking how Cljs asset-path works. Boot-reload does it completely differently. Perhaps this makes sense.

**Comment by alesguzik** [comment]
Yes, they are completely different. That's why I have it is set to "/application.out" for cljs and to "public" for reload - they have same name, but slightly different meaning.

**Comment by alesguzik** [comment]
Oops, pressed wrong button.

**Comment by Deraen** [comment]
Okay, seems to work. Thanks.

**Comment by alesguzik** [comment]
Thanks

**Pull request merged**
