### PR TITLE
HUD

### PR DESCRIPTION
**Pull request by martinklepsch**
Work in progress of a Figwheel style HUD to inform users of compiler warnings and exceptions.

- Maybe something like `parse-warnings` should be done by the `cljs` task. In the current state there is not much being done with the extra information. Potentially it would be interesting to use the additional information to emphasize the more important bits.
- Some of the functions are missing `!` at the end, will add them.
- Alternative suggestions to names like `send-visual`, `display` etc. are welcome.

### CODE REVIEW

**Comment by martinklepsch** [comment]
screenshot 2015-09-24 15 33 04

screenshot 2015-09-24 15 33 17

**Comment by Deraen** [comment]
It looks awesome!

**Comment by Deraen** [comment]
One feature Figwheel has: Clicking warning/error will open the source file in your editor. It works by sending an message from browser to server through websocket containg the file name and line number and the server then runs configured command (something `emacsclient +linenumber:column file`).

**Comment by Deraen** [comment]
No need to implement it now but I guess it should be quite easy once the data sent from server contains necessary data in addition to the message.

**Pull request merged**
