### PR TITLE
Support multiple reloads in a pipeline; helps #41

### PR DESCRIPTION
**Pull request by samroberton**
This commit does two things:

1. Use a gensym'd name for the (former) `adzerk.boot_reload` ns, so that
different `reload` tasks in a single pipeline can operate independently
without collisions.

2. Introduce an optional `:only-by-re` option, and when it's set, only
send reloads of files in the fileset which match the given patterns.
This presents a solution to the problem in #41, in that reloads can be
limited to the artefacts from a single build's compilation artefacts,
avoiding the need for the `reload` task to do dependency tracking.

For example:

    (deftask dev []
      (comp (watch)
            (reload :ids #{"react-www"}
                    :only-by-re [#"^react-www\.out/.*"]
                    :on-jsload 'my.react-www.app/reload)
            (reload :ids #{"react-native"}
                    :only-by-re [#"^react-native\.out/.*"]
                    :on-jsload 'my.react-native.app/reload)
            (cljs :ids #{"react-www" "react-native"}
                  :optimizations :none)))

### CODE REVIEW

**Comment by ejlo** [comment]
This looks really useful!

Any plans to get it merged?

**Comment by samroberton** [comment]
To the extent that it might be useful to anyone even without having been merged, you can use the following dependency to test it out:  `[org.clojars.samroberton/boot-reload "0.4.7-SNAPSHOT"]`.

**Comment by Deraen** [comment]
Hmm, I guess we could merge this. I have other plans to eventually fix #41 without need for users to set any options etc. But I guess we can add the option for now and remove it when I finally have time to look into refactoring the implementation.

**Comment by Deraen** [comment]
@samroberton Could you rebase this against the latest commit?

**Comment by samroberton** [comment]
No problems:  I've just pushed a rebased commit (which I've also put up on Clojars as `[org.clojars.samroberton/boot-reload "0.4.9-SNAPSHOT"]`, in case that happens to be useful to anyone other than myself).

**Pull request merged**
