### PR TITLE
check socket is open before transmit

### PR DESCRIPTION
**Pull request by pandeiro**
Addresses #25.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Even though some of the reasoning for #25 is no longer applicable this seems to be good to do anyways? @Deraen

**Comment by pandeiro** [comment]
Question: can boot-cljs produce multiple :optimizations :none builds currently? The issue is still that cljs_deps.js file the clojurescript emits, right?

**Comment by pandeiro** [comment]
(Regardless, if the cost of this is just one or two function calls, I think it makes sense to include. I'm using it and notice no perf difference.)

**Comment by martinklepsch** [comment]
@pandeiro not sure if I understand correctly but with multiple `.cljs.edn` files you could produce multiple `:none` builds already no? In the boot-cljs/next branch each `cljs` call will be tied to a `.cljs.edn` file allowing different optimization levels per build as well.

**Comment by pandeiro** [comment]
@martinklepsch: Last I checked (may be wrong), each build would produce a file with three names cljs_deps.js (the shim created by the cljs compiler to goog.require() everything). These would clobber each other in target.

**Comment by pandeiro** [comment]
s/three names/the name

Sorry, I'm on mobile.

**Pull request merged**
